# Generated by Django 3.0.5 on 2020-05-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_post_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='post_image')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='cover_image',
        ),
    ]
