# Generated by Django 3.0.5 on 2020-05-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200505_0037'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post_image',
        ),
        migrations.AddField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_image'),
        ),
    ]
